name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 7"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: oldgrandpavanu/cloudflarednsupdateservice:latest, oldgrandpavanu/cloudflarednsupdateservice:${{ steps.date.outputs.date }}
